### PR TITLE
bugfix: getArkSurvey

### PR DESCRIPTION
**Pull request by anaim**

### CODE REVIEW

**Review by reno1979 — APPROVED** [review]
looks good to me, ow wait I ran the e2e and it failed

**Review by reno1979 — COMMENTED** [review]
ow one more ::

```
[Nest] 30243  - 04/03/2023, 2:10:28 PM VERBOSE [Keycloak] Resource granted due to role(s)

/home/rene/Projects/bmi-aip-graphql-service/src/schema/ark-survey/ark-survey.repository.ts:137
                        throw new Error('No survey found.');
         ^
Error: No survey found.
    at ArkSurveyRepository.updateSurvey (/home/rene/Projects/bmi-aip-graphql-service/src/schema/ark-survey/ark-survey.repository.ts:137:10)

```

**Review by fortunato — COMMENTED** [review]
I suggest we merge this one instead:
https://github.com/Amsterdam/bmi-aip-graphql-service/pull/339

**Comment by anaim** [comment]
Bug is gefixt in https://github.com/Amsterdam/bmi-aip-graphql-service/pull/339/files

**Comment by anaim** [comment]
Bugfix: https://github.com/Amsterdam/bmi-aip-graphql-service/pull/339/files

**Pull request closed without merging**
